### ISSUE TITLE
Environment variable not set in DataSpell console

### ISSUE THREAD

**Issue by jblugagne** [pavelzw/pixi-pycharm#51]
## Description

I'm using DataSpell which is very close to PyCharm. I used pixi-pycharm to set up an environment that I created via pixi as interpreter. The interpreter works fine for the most part. 

My problem is that I have the following in my `pyproject.toml`:
```
[tool.pixi.feature.torch]
activation = { env = { KERAS_BACKEND = "torch" } }
```

and
```
[tool.pixi.environments]
pixi-torch-gpu = { features = ["cuda", "torch-gpu", "torch"], solve-group = "torch" }
```
with the first part meant to set the `$KERAS_BACKEND` environment variable to `torch` upon activation.

When I run `pixi shell -e pixi-torch-gpu` in my terminal, it works fine and I have `$KERAS_BACKEND` set to `torch`.

However in DataSpell, `os.environ["KERAS_BACKEND"]` gives me `KeyError: 'KERAS_BACKEND'`. Setting `os.environ["KERAS_BACKEND"] = "torch"` manually works fine, the interpreter can import all the libraries and my code runs as it should. Is there a way to get the environment variable without having to manually set it up in the DataSpell console settings?

## Versions

```bash
❯ pixi --version
0.39.0
❯ pixi list | grep pixi-pycharm
0.0.8
```

PyCharm version: DataSpell 2024.2.2

Platform: Fedora Linux 41

## Logs

```
Attempting to run: ['info', '--envs', '--json']
Attempting to run: ['run', '-n', 'pixi-torch-gpu', '--no-capture-output', 'python', '-c', 'import sys; print(sys.executable)']
Attempting to run: ['list', '-n', 'pixi-torch-gpu']
Attempting to run: ['info', '--envs', '--json']
Attempting to run: ['list', '-n', 'pixi-torch-gpu']
Attempting to run: ['list', '-n', 'pixi-torch-gpu']
Attempting to run: ['list', '-n', 'pixi-torch-gpu']
Attempting to run: ['info', '--envs', '--json']
Attempting to run: ['info', '--envs', '--json']
Attempting to run: ['info', '--envs', '--json']
Attempting to run: ['info', '--envs', '--json']
```

**Comment by pavelzw** [comment]
Yeah, this is a skill issue on pycharm's end unfortunately.
You can see from the pixi-pycharm logs that pycharm tries to invoke `conda run -n pixi-torch-gpu --no-capture-output python -c "import sys; print(sys.executable)"` to get the python interpreter path.
With this path, it then just runs your python code.
So all environment variables that are set in activation scripts or specified in pixi.toml are just ignored by pycharm since they just execute the python binary directly instead of going through `conda run`.

There is unfortunately nothing we can do here to go around this and you need to re-specify this env variable in your run configurations.
